language: node_js
node_js:
- node
script:
- npm run deploy
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
env:
  global:
    secure: WRQKAmcZ+UxVqGUr/cS1fHcMq66TasskKjLkuf98LX9RIox7p/ivlzssELDmDcIP/3Y5RS1JLrtnEavR12gioVzBeGBRt57ReGCPszvuzylmr4ho2m1pvRLk8pmDHzlR6oxRqk5HoBVmapy4FE+AtL+ixRSn+MnJs5Vf1ZZosXuzm4rqs/xMTZppvcOVfXcnLb1Ss4dDNcAyBSEla/W5sgk9g1FPvnAY7OZvLpj6fRp1nXgybTRQOYVTcZGX06pJ/ea0YskcDgMlLqbxMpOfxepcma3QF+nhVMHg6ztojjnB15rHYuPUZuFzBJ7/nTBptCe5okqRQGxsEnoAv/WFJXYNIvkbb4sypZxi9eHyebELMEUJTmjrLNyAgyFqHkS/Gx01/UfFtbcIorToWP43Mde2dFejuHdLoTPrzA7jfhewWdaWHpf5d0ky4vIGHQRqpCZHOVcgFD809s5odKPe1HARdbHN5n2Rhs7qjwgZkHrUZRr911clxcvdcnYKsSMMLFmh/1maJ6xBkAYcmk2gPraqwNngFXlXm5395jMdYfbfS9W5+5LUzvid9fwbRDN+eQkVuEfkjhdXCqRynny5I6tO1+wHufviEwmbq+GqaFYnFlxrwUnecLP8biaT3QzP3lVWh041xBGbCr7GbzMdIx1LQd1zOKIubIGklfol27U=
